### ISSUE TITLE
Automatically fall back to different behavior when `O_TMPFILE` doesn't work

### ISSUE THREAD

**Issue by jplatte** [andreacorbellini/rust-atomic-write-file#3]
Apparently `overlayfs`, used by container software, doesn't support unnamed tempfiles: https://github.com/launchbadge/sqlx/issues/2908

It would be nice to be able to easily use `O_TMPFILE` when it *is* supported, and fall back to a different behavior when it isn't. Currently, there's just the Cargo feature (and a library can't be sure that it's disabled, since some other package in an application's dependency tree might activate the it).

**Comment by abonander** [comment]
It's conceivable that some users would prefer the operation to fail loudly instead of silently falling back, which I'm thinking might be a reason why it's a Cargo feature in the first place.

IMO, the option to use unnamed tempfiles should be a flag on `OpenOptions`, not a Cargo feature. 

A Cargo feature to _enable_ the functionality makes sense if it requires additional dependencies, and the flag can default to `true` so that it can be added backwards compatibly. 

With that, it would be relatively easy to implement the fallback in user code if it's not desirable to make it automatic.

Alternatively, you could just add a second flag to toggle the fallback behavior.

**Comment by andreacorbellini** [comment]
Hi, thanks for letting me know. I was not aware that overlayfs did not
support unnamed temporary files. I agree that support for them should be
detected at runtime, as people writing software using this crate can't know
in advance where their software will run.

I'm not sure a configuration option is strictly needed: I would prefer the
crate to do the "right thing" by default without having the developer
worrying too much about the internal implementation details. In other
words, I'm leaning more on the side of automatic feature detection, rather
than configuration. Having said that, it doesn't hurt to add a
configuration flag, so I wouldn't oppose that either.

I'm going to work on this issue this or next week if time permits.

**Comment by abonander** [comment]
It's specified to return `ENOTSUP` so you should be able to just detect that and retry without the flag.

**Comment by andreacorbellini** [comment]
Cool, thanks for providing the errno. That's very unambiguous so it'll be
easy to detect (lack of) support for unnamed temporary files, it shouldn't
take too much effort.

**Comment by andreacorbellini** [comment]
Released a fix in [atomic-write-file 0.1.2](https://crates.io/crates/atomic-write-file/0.1.2).

With this new release, `AtomicWriteFile` will first attempt to create an anonymous temporary file. If that fails (either because the filesystem does not have support for it, or because the Linux kernel is too old), then a named temporary file is used instead, using the generic Unix implementation. I hope this helps, please let me know if further improvement is required.

I've also extended the GitHub CI suite to run tests on overlayfs ([example](https://github.com/andreacorbellini/rust-atomic-write-file/actions/runs/7051044288/job/19193070220)), so that I can be notified if any future change breaks overlayfs support.

Last but not least, in the future I plan to add the ability to customize the name/pattern of the temporary file, which is something I think you might be interested in.

Hope this helps!
