### ISSUE TITLE
`os error 5` when open `AtomicWriteFile` with `tempfile`

### ISSUE THREAD

**Issue by xuxiaocheng0201** [andreacorbellini/rust-atomic-write-file#7]
It returns an error when commit, opening with `tempfile::NamedTempFile.path()`.
Access is denied. (os error 5)

# dependencies
```text
├── anyhow v1.0.81
├── atomic-write-file v0.1.3
│   └── rand v0.8.5
│       ├── rand_chacha v0.3.1
│       │   ├── ppv-lite86 v0.2.17
│       │   └── rand_core v0.6.4
│       │       └── getrandom v0.2.14
│       │           └── cfg-if v1.0.0
│       └── rand_core v0.6.4 (*)
└── tempfile v3.10.1
    ├── cfg-if v1.0.0
    ├── fastrand v2.0.2
    └── windows-sys v0.52.0
        └── windows-targets v0.52.4
            └── windows_x86_64_msvc v0.52.4
```
# Platform
Windows
# Code
```rust
use anyhow::Result;
use atomic_write_file::AtomicWriteFile;
use tempfile::NamedTempFile;

fn main() -> Result<()> {
    let file = NamedTempFile::new()?;
    let path = file.path();
    let atomic = AtomicWriteFile::open(path)?;
    atomic.commit()?;
    Ok(())
}
```
# Output
```text
Error: 拒绝访问。 (os error 5)
```

**Comment by andreacorbellini** [comment]
Thanks for reporting this, and for including the snippet to reproduce the issue. I did some investigation, and my conclusion is that this happens because, in Windows, you cannot remove a file while it's open.

In this particular case, `file` is open when `atomic.commit()` is called. `atomic.commit()` will attempt to replace the file at `path`, but because it's open, Windows does not allow that, and the operation fails.

The following code solves the problem:

```rust
fn main() -> Result<()> {
    let file = NamedTempFile::new()?;
    let path = file.path();
    let atomic = AtomicWriteFile::open(path)?;
    drop(file); // <<<
    atomic.commit()?;
    Ok(())
}
```

So, this is not really a bug of atomic-write-file, but rather a Windows limitation. I'll keep this issue open to remind me to document this behavior in the documentation of atomic-write-file.

**Comment by xuxiaocheng0201** [comment]
The reason analysis is correct, and the modifications you provided are also acceptable, but there are still some questions as follows:

1. Is the behaviour of `drop(file);` safe? According to the [`Design`](https://docs.rs/tempfile/3.10.1/tempfile/#design) chapter, `TempDir and NamedTempFile both rely on Rust destructors for cleanup.` Actually, it removes the temp file when drop. So it's counterintuitive dropping tempfile before commit.
2. In real life, a function usually only accept the path like `impl AsRef<Path>`. There is no way to drop the temp file. Drop the temp file before calling the function? But reopenning the temp file after the function returns is troublesome.

So is there a better way to achieve atomic writing?

**Comment by andreacorbellini** [comment]
On Windows you cannot replace or delete a file wile it's open, so you need a solution where the `NamedTempFile` does not exist at the same time while `AtomicWriteFile` exist. I can think of at least two such solutions:

1.  Use [`NamedTempFile::into_temp_path()`](https://docs.rs/tempfile/3.10.1/tempfile/struct.NamedTempFile.html#method.into_temp_path) to close the temporary file without removing it, like this:

    ```rust
    let tmpfile = NamedTempFile::new()?;
    let path = tmpfile.into_temp_path();
    let atomic = AtomicWriteFile::open(path)?;
    atomic.commit()?;
    // `path` is dropped automatically at the end of the scope, removing the temporary file
    ```

1.  Use [`tempdir()`](https://docs.rs/tempfile/3.10.1/tempfile/fn.tempdir.html) to create a temporary directory, instead of a temporary file, and create a new file inside the temporary directory:

    ```rust
    let tmpdir = tempdir()?;
    let path = tmpdir.path().join("file");
    let atomic = AtomicWriteFile::open(path)?;
    atomic.commit()?;
    // `path` is dropped automatically at the end of the scope, removing the temporary directory and any file within
    ```

Having said that, however, I would question whether you really need to atomically write to a temporary file: a temporary file created with `NamedTempFile::new()` has a random (unpredictable) name, hence no process should use it until its presence is disclosed. You could design your application so that you open the temporary file, write into it unatomically, and only then disclose its location to other processes. I do not have context on your application, so take this just a suggestion.

**Comment by xuxiaocheng0201** [comment]
Thanks for your solutions.
I just do it in tests.

**Comment by andreacorbellini** [comment]
Thanks for reporting this issue & contributing a fix. The fix is now part of the latest release: https://crates.io/crates/atomic-write-file/0.2.2

To catch similar issues in the future, I extended the GitHub workflow to cross-compile for multiple platforms and ABIs (including `androideabi`). You can see an example run here: https://github.com/andreacorbellini/rust-atomic-write-file/actions/runs/11654980927
